config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
    resources :books, :writers do
        resources :comments, only: [:create, :destroy]
      resources :votes, only: [:create, :update]
    end
    root 'books#index'

    resources :categories
    devise_for :users

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true
  validates :published_at ,presence: true
  validates :description, presence: true
  validates :publishing_house, presence: true

  belongs_to :category
  belongs_to :writer
  has_many :statuses
  has_many :comments
  has_many :votes
  has_and_belongs_to_many :tags

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  def average_rating
    rating = votes.average(:rating)
    rating ? rating.to_s : "0.0"
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    load_form_data
  end

  # GET /books/new
  def new
    @book = Book.new
    load_form_data
  end

  # GET /books/1/edit
  def edit
    load_form_data
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        load_form_data
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        load_form_data
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :published_at, :description, :publishing_house, :link, :category_id, :writer_id, :status_id, :image, tag_ids: [])
    end

    def load_form_data
      @categories = Category.all.collect {|c| [c.name, c.id ] }
      @writers = Writer.all.collect {|w| [w.name, w.id ] }
      @tags = Tag.all
      @statuses = Status.all.collect {|s| [s.name , s.id]}
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(book,html: { multipart: true }) do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, as: :file %><br />
    </div>

    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :published_at %>
    <%= f.date_select :published_at %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :publishing_house %>
    <%= f.text_field :publishing_house %>
  </div>

  <div class="field">
    <%= f.label :link %>
    <%= f.text_field :link %>
  </div>

  <div class="field">
    <%= f.select :category_id, @categories %>
  </div>

  <div class="field">
    <%= f.select :status_id, @statuses %>
  </div>

  <div class="field">
     <%= f.select :writer_id, @writers %>
  </div>

  <div>
    <%= f.collection_check_boxes(:tag_ids, @tags, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= image_tag("bookbuddylogo.png"), class="header"%>Books</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Published at</th>
      <th>Description</th>
      <th>Publishing house</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to (image_tag book.image.url(:medium)), book %></td>
        <td><%= book.name %></td>
        <td><%= book.published_at %></td>
        <td><%= book.description %></td>
        <td><%= book.publishing_house %></td>
        <td><%= book.link %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @book.image.url(:medium) %>
</p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @book.published_at %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Publishing house:</strong>
  <%= @book.publishing_house %>
</p>

<p>
  <strong>Link:</strong>
  <%= @book.link %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category.name %>
</p>

<p>
  <strong>Writer:</strong>
  <%=link_to  @book.writer.name , writer_path(@book.writer) %>

   <% if @book.statuses.present? %>
  <%= @book.status.name %>
  <% end%>

  <%= form_for(@book,html: { multipart: true }) do |f| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
  <strong>Durum:</strong> <%= f.select :status_id, @statuses %>
  </div>
      <%= f.submit 'Onayla' %>
 <% end %>

</p>

<p>
  <b>Average Rating: </b><%= @book.average_rating %><br />
</p>

<h4>Rating:</h4>
<%= render 'votes/form' %>

<br><br>
<h1>Comments</h1>
<% @book.comments.each do |comment| %>
    <p><%= comment.body %></p>
    <% if current_user == comment.user %>
        <small><%= link_to "Delete", book_comment_path(@book, comment), method: :delete %></small>
    <% end %>
<% end %>

<h1>Write a comment</h1>
<%= form_for [@book, @book.comments.build] do |f| %>
  <%= f.text_area :body, rows: 5 %><br>
  <%= f.submit 'Send' %>
<% end %>

<b>Tags: </b><%= @book.tags.collect {|x| x.name }.join(", ")%> <br/>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>